### ISSUE TITLE
4.22 update?

### ISSUE THREAD

**Issue by Pirog17000** [devdad/SimplexNoise#11]
Got it working with 4.21 but when I'm trying to update the project to 4.22, the plugin fails to compile at launch. Any workaround?

**Comment by Saphirah** [comment]
That usually happens when you try to update a project, all custom plugins break. 4.22 is working though. My workaround is that i create a new 4.22 project and move all the config and content files.

**Comment by devdad** [comment]
You can now update to new version 1.2.0, there is a binary version in the release section.
