### ISSUE TITLE
In range and Scaled not working as intended.

### ISSUE THREAD

**Issue by Agent-Sckit** [devdad/SimplexNoise#15]
Hi @devdad,

Just stumbled on a problem here. Idk if this is due to the updates but the thing is the in-range function and the Scaled does not work as expected? It still yields values that are out of range. See attached photos. I'm using the 4.24. I'm not into c++ so I thought it might be helpful to request a check up from the creator. 

Thanks a lot! 
(attached photos are the screenshot of the yields of the In-range function)

![Noise in range](https://user-images.githubusercontent.com/26269671/72214522-d7069a00-353e-11ea-8666-9a51f8ec4e33.PNG)
![Actor](https://user-images.githubusercontent.com/26269671/72214523-d7069a00-353e-11ea-820e-8c4ef5bd683b.PNG)
![Output Log](https://user-images.githubusercontent.com/26269671/72214524-d79f3080-353e-11ea-8003-8ab4a72f2744.PNG)

**Comment by devdad** [comment]
Thanks, I will check it.

**Comment by devdad** [comment]
Problem is solved you have to update to version 1.2.0 ;)
