### ISSUE TITLE
Problems using Simplex Noise

### ISSUE THREAD

**Issue by BladeDev1** [devdad/SimplexNoise#17]
I've made something from this tutorial using the plugin : https://www.youtube.com/watch?v=1VLVNYR-lRc&t=241s 

I managed to update the code as that's a 2018 tutorial, the 2d simplex noise gained a new node since that time, and when I redid the code in a new version of the engine the noise only appears in 2d instead of 3d. Could I get assistance on how to make it work or maybe have assistance with how to make it work? There's absolutely no tutorials and I'm utterly lost

**Comment by devdad** [comment]
I will create a few video tutorials as well as documentation wiki, very soon. Thanks a lot and by the way make sure to update to latest version 1.2.0
