### ISSUE TITLE
Will not build with 5.1

### ISSUE THREAD

**Issue by ghost** [devdad/SimplexNoise#19]
Hello, looks like this doesn't want to build with 5.1. Trying to upgrade my project and its telling me it can't compile. I just got done cloning what jimshalo10 had in the pull request for 5.0 but that's a no go as well. I was already using this for 5.0 however, its just 5.1 that isn't working now. I understand that this is originally for 4 but considering that it was working on 5.0 is there a way to make this work? I've been trying to compare uplugin files to see what need to but changed so if I stumble into anything I'll update.

**Comment by Lazarus-glhf** [comment]
I downloaded the source code file from release , extract it to the plugins folder and everything works fine in 5.1.1. Just try the source code file, hope it works for you.

**Comment by beven7** [comment]
Huh you're right.. I wonder why it originally wasn't building for me. Thanks for the heads up, everything is working great!

**Comment by ghost** [comment]
Huh you're right.. I wonder why it originally wasn't building for me. Thanks for the heads up, everything is working great!
