### ISSUE TITLE
Errors when building in Development/Shipping

### ISSUE THREAD

**Issue by bswenson2** [devdad/SimplexNoise#7]
Hi,
I really like the results with your plugin, but I'm getting some compile errors when I Build in Development or Shipping. Building Development Editor works fine though.

Log attached
[UnrealBuildTool-2018.03.19-21.53.46.txt](https://github.com/devdad/SimplexNoise/files/1827625/UnrealBuildTool-2018.03.19-21.53.46.txt)

**Comment by Jordonbc** [comment]
Finally after months of trying to fix this issue, Success!
I have opened a pull request from my fork that's fixed this issue. Hopefully it will me merged.

[https://github.com/Jordonbc/SimplexNoise](https://github.com/Jordonbc/SimplexNoise)

**Comment by bswenson2** [comment]
Awesome, that looks like it fixed it
