### ISSUE TITLE
What is the project license?

### ISSUE THREAD

**Issue by KelSolaar** [devdad/SimplexNoise#9]
Hi @devdad,

Thanks for your UE4 plugin!

I could not find any license in your project, would it be possible to get one added please?

Cheers,

Thomas

**Comment by devdad** [comment]
Hi, thanks for using it actually you can find in every source file this piece of text:

SimplexNoise 1.0.0
-----
DevDad - Afan Olovcic @ www.art-and-code.com - 08/12/2015
This algorithm was originally designed by Ken Perlin, but my code has been
adapted and extended from the implementation written by Stefan Gustavson (stegu@itn.liu.se)
and modified to fit to Unreal Engine 4
* This is a clean, fast, modern and free Perlin Simplex noise function.
* If we change float to double it could be even faster but there is no double type in Blueprint
* All Public Functions are BlueprintCallable so they can be used in every blueprint

**From DevDad and Dedicated to you and Unreal Community
Use it free for what ever you want
I only request that you mention me in the credits for your game in the way that feels most appropriate to you.**

**Comment by thomasmansencal** [comment]
Hi @devdad,

Thanks for taking time to answer, I indeed saw the headers but I don't think they can really replace a proper license from a legal standpoint, hence my question! :)

Cheers,

Thomas

**Comment by devdad** [comment]
Ok then, use it  don't worry, I'll add the license file ;)

**Comment by thomasmansencal** [comment]
Awesome @devdad, hugely appreciated!

**Comment by devdad** [comment]
Done code is now under Mit License,  Cheers!

**Comment by thomasmansencal** [comment]
Thanks a lot! Closing the issue.
